spring.application.name=subscription

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

renewal.scheduler.interval-ms=${RENEWAL_INTERVAL:3600000}
renewal.scheduler.enabled=${RENEWAL_ENABLED:true}

dunning.max-retries=3
dunning.grace-period-days=7
dunning.retry-intervals-hours=24,48,72
#dunning.scheduler.interval-ms=${DUNNING_INTERVAL:1800000}
dunning.scheduler.interval-ms=${DUNNING_INTERVAL:10000}